#!/usr/bin/env python3
"""
PIPBOI — first-run setup wizard.

Run me:   python3 setup.py

I ask for your Helius (required) and Bitquery (optional) API keys, generate
strong dashboard secrets for you, and write your .env. No keys are sent anywhere
— everything stays in your local .env (which is gitignored). Re-run me anytime
to update settings.

Stdlib-only, so it runs before `pip install`.
"""
import os
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV = ROOT.parent / ".env"   # .env lives at the repo root, one level up from src/

G = "\033[1;32m"; D = "\033[2;32m"; Y = "\033[1;33m"; R = "\033[0m"; B = "\033[1m"


def banner():
    print(f"""{G}
  ┌──────────────────────────────────────────────────┐
  │   ⚙   D A T B O I         —   S E T U P            │
  └──────────────────────────────────────────────────┘{R}
""")


def ask(prompt, default="", secret_default=False):
    suffix = f" {D}[{default}]{R}" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


def yes(prompt, default=True):
    d = "Y/n" if default else "y/N"
    v = input(f"{prompt} {D}[{d}]{R}: ").strip().lower()
    if not v:
        return default
    return v.startswith("y")


def load_existing():
    cfg = {}
    if ENV.exists():
        for line in ENV.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                cfg[k.strip()] = v.strip()
    return cfg


def main():
    banner()
    existing = load_existing()
    if existing:
        print(f"{Y}An .env already exists — I'll keep your current values as defaults.{R}\n")

    print(f"{B}1) Helius API key{R}  (required — your connection to Solana)")
    print(f"   {D}Free key at https://dashboard.helius.dev → create a project → copy the key{R}")
    helius = ask("   Helius API key", existing.get("HELIUS_API_KEY", ""))
    while not helius:
        print(f"   {Y}Helius key is required to run.{R}")
        helius = ask("   Helius API key")

    print(f"\n{B}2) Bitquery API key{R}  (optional — real-time candidate feed)")
    print(f"   {D}Free key at https://account.bitquery.io → API keys (v2 GraphQL X-API-KEY).{R}")
    print(f"   {D}Leave blank to skip — the bot runs fine without it.{R}")
    bitquery = ask("   Bitquery API key", existing.get("BITQUERY_API_KEY", ""))

    print(f"\n{B}3) Wallet{R}  (the SOL the bot trades with)")
    print(f"   {D}You don't need a wallet yet — when you 'Activate' a bot in the dashboard{R}")
    print(f"   {D}it generates a fresh wallet for you and shows its address to fund.{R}")
    kp_default = existing.get("KEYPAIR_PATH", "~/.config/solana/pipboi.json")
    keypair = ask("   Default keypair path", kp_default)

    print(f"\n{B}4) Capital reference (USD){R}  {D}(actual size comes from your live SOL balance){R}")
    capital = ask("   TOTAL_CAPITAL_USD", existing.get("TOTAL_CAPITAL_USD", "100.0"))

    print(f"\n{B}5) RPC node{R}  {D}(optional — leave blank to use your Helius endpoint){R}")
    print(f"   {D}Paste a custom RPC URL here to route through a different node.{R}")
    rpc = ask("   RPC_URL", existing.get("RPC_URL", ""))

    # Dashboard secrets — generated, not asked.
    dash_secret = existing.get("DASHBOARD_SECRET") or secrets.token_urlsafe(32)
    dash_pin = existing.get("DASHBOARD_PIN") or secrets.token_urlsafe(6)

    lines = [
        "# Generated by setup.py — edit freely, but NEVER commit this file.",
        f"HELIUS_API_KEY={helius}",
        f"KEYPAIR_PATH={keypair}",
        f"TOTAL_CAPITAL_USD={capital}",
        "",
        f"DASHBOARD_SECRET={dash_secret}",
        f"DASHBOARD_PIN={dash_pin}",
    ]
    if rpc:
        lines += ["", f"RPC_URL={rpc}"]
    if bitquery:
        lines += ["", f"BITQUERY_API_KEY={bitquery}"]
    # carry forward any other keys the user had set
    for k, v in existing.items():
        if k not in {"HELIUS_API_KEY", "KEYPAIR_PATH", "TOTAL_CAPITAL_USD",
                     "DASHBOARD_SECRET", "DASHBOARD_PIN", "RPC_URL", "BITQUERY_API_KEY"} and v:
            lines.append(f"{k}={v}")
    lines.append("")

    ENV.write_text("\n".join(lines))
    try:
        os.chmod(ENV, 0o600)
    except OSError:
        pass

    print(f"""
{G}✓ Wrote .env{R}  (dashboard PIN: {B}{dash_pin}{R}  — you'll enter this in the dashboard to unlock admin actions)

{B}Next steps:{R}
  1) {D}python3 -m venv .venv && source .venv/bin/activate{R}
  2) {D}pip install -r requirements.txt{R}
  3) {D}./run.sh{R}   →  open  {G}http://localhost:8080{R}
  4) In the dashboard, unlock with your PIN and click {B}Activate{R} on a bot —
     it generates a wallet, shows the address to fund, and starts trading.

{Y}⚠ Fund the wallet with a SMALL amount you can afford to lose. This is real money.{R}
""")


def bootstrap():
    """Non-interactive: create a minimal .env with generated secrets if none exists,
    so the dashboard can boot and the user finishes setup in the browser at /setup."""
    if ENV.exists():
        return
    dash_secret = secrets.token_urlsafe(32)
    dash_pin = secrets.token_urlsafe(6)
    ENV.write_text("\n".join([
        "# Auto-created on first run. Finish setup in your browser (enter API keys) at",
        "# http://localhost:8080  — or run: python3 setup.py . Never commit this file.",
        "HELIUS_API_KEY=",
        "KEYPAIR_PATH=~/.config/solana/pipboi.json",
        "TOTAL_CAPITAL_USD=100.0",
        "",
        f"DASHBOARD_SECRET={dash_secret}",
        f"DASHBOARD_PIN={dash_pin}",
        "",
    ]))
    try:
        os.chmod(ENV, 0o600)
    except OSError:
        pass
    print(f"{G}First-run config created.{R}")
    print(f"  → Finish setup in your browser:  {G}http://localhost:8080{R}")
    print(f"  → Your dashboard PIN:  {B}{dash_pin}{R}  (enter this to unlock + save your keys)\n")


if __name__ == "__main__":
    import sys
    if "--bootstrap" in sys.argv:
        bootstrap()
    else:
        try:
            main()
        except (KeyboardInterrupt, EOFError):
            print("\nSetup cancelled.")
